### PR TITLE
Fix spacing in logo-facebook id

### LINKED ISSUE #341: Accessibility: aria-labelledby: logo-facebook in footer
There's an `aria-labelledby` but no element with the id `logo-facebook`. This causes a failure with the axe-core-rspec integration on pulfalight.

Selector: svg[aria-labelledby="logo-facebook"]

This appears to be a wcag2a violation.

Perhaps just use `aria-label` instead.

### PR DESCRIPTION
**Pull request by hackmastera**
closes #341

### CODE REVIEW

File: src/logos/LogoFacebook.vue [hunk 1]
```diff
@@ -5,10 +5,10 @@
     :height="height"
     viewBox="0 0 24 24"
     preserveAspectRatio="xMinYMid"
-    aria-labelledby="logo-facebook"
+    aria-label="logo-facebook"
```
Comment (sdellis) [inline src/logos/LogoFacebook.vue:8]: @hackmastera According to [this article](https://css-tricks.com/accessible-svgs/), all we need to change is `role="presentation"` to `role="img"`. I can make this change, but since some accessibility recommendations are not normative, can you share what prompted you to make these changes for comparison?

Comment (hackmastera) [reply src/logos/LogoFacebook.vue]: @sdellis sorry about that! We didn't see the title at first and so we made it `aria-label`. Then we noticed the title and the typo in the id. Forgot to change back to labelled-by. Thanks for catching it!

So that's fixed now and we went ahead and added the role change that you suggested. Take another look?

Comment (sdellis) [reply src/logos/LogoFacebook.vue]: @hackmastera LGTM! I fixed the role in the other icons as well. Will merge now.
